# Dimension Unlock Configuration
# Date format: YYYY-MM-DD HH:mm:ss
max_hearts: 20
dimensions:
  nether:
    unlock-date: "2026-03-02 16:00:00"
    locked-message: "A Nether le van zárva! Megnyílik: 2026. 03. 22. 16:00."
  the_end:
    unlock-date: "2026-03-14 10:00:00"
    locked-message: "Az End le van zárva! Megnyílik: 2026. 03. 14. 10:00."
